### ISSUE TITLE
Review- User Auth 

### ISSUE THREAD

**Issue by jchen143** [jchen143/lunch-buddy#2]
Hi Justin. My authentication MVP is ready to be reviewed. Thanks!

**Comment by jmeyer90** [comment]
Tasks to complete:

Styling:
- The left hand side of the splash page should have an image with no text over it. All text should be on a solid background on the right hand side of the splash page.
- On the splash page, the text above our form input fields should be larger.
- On the splash page, the text inside the input field should be larger.
- On the splash page, the text inside the buttons should be larger.
- On the login page, please find fonts which more closely resemble whats on the page.
- On the login page, the modal is lower on the page.
- On the login page, the text inside the input field should be larger.
- On the login page, the text inside the buttons should be larger.

Functionality:
- On logging in, the Log in button should no longer appear on the Navbar.
- When signing up, we are redirected to an entirely new page. Even if we use a partial for our forms, we should still display them appropriately.

**Comment by jmeyer90** [comment]
I found error, and as soon as this is fixed you can move on.
- Cannot navigate from the login page to the homepage without logging in. This is most likely due to an unnecessary Auth or Protected route.

Everything else looks great! Features to be added as a bonus:

- Custom errors to be rendered in red text below the input fields.
- Choose a background image on your homepage or a font-color which would make the white text more readable.
